plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

android {
    namespace = 'org.godotengine.godot_gradle_build_environment'
    compileSdk = 36
    ndkVersion = '29.0.14206865'

    def keystoreFile = System.getenv("GABE_RELEASE_KEYSTORE_FILE")

    sourceSets {
        main {
            jniLibs.srcDirs += [
                '../thirdparty/proot/build/bin',
            ]
        }
    }

    defaultConfig {
        applicationId = "org.godotengine.godot_gradle_build_environment.saftest"
        minSdk = 24
        targetSdk = 36
        versionCode = 7
        versionName = "1.0.1-saftest1"

        ndk {
            abiFilters.add("arm64-v8a")
        }

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    if (keystoreFile != null) {
        signingConfigs {
            release {
                storeFile file(System.getenv("GABE_RELEASE_KEYSTORE_FILE"))
                storePassword System.getenv("GABE_RELEASE_STORE_PASSWORD")
                keyAlias System.getenv("GABE_RELEASE_KEY_ALIAS")
                keyPassword System.getenv("GABE_RELEASE_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            if (keystoreFile != null) {
                signingConfig signingConfigs.release
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    flavorDimensions = ["android_distribution"]
    productFlavors {
        android {
            dimension "android_distribution"
            def godotEditorPackage = "org.godotengine.editor.v4.saftest"
            manifestPlaceholders = [editorPackage: godotEditorPackage]
            buildConfigField("String", "EDITOR_PACKAGE", "\"${godotEditorPackage}\"")
            getIsDefault().set(true)
        }
        horizonos {
            dimension "android_distribution"
            versionNameSuffix "-horizonos"
            def godotEditorPackage = "org.godotengine.editor.v4.meta"
            manifestPlaceholders = [editorPackage: godotEditorPackage]
            buildConfigField("String", "EDITOR_PACKAGE", "\"${godotEditorPackage}\"")
        }
        picoos {
            dimension "android_distribution"
            versionNameSuffix "-picoos"
            def godotEditorPackage = "org.godotengine.editor.v4.pico"
            manifestPlaceholders = [editorPackage: godotEditorPackage]
            buildConfigField("String", "EDITOR_PACKAGE", "\"${godotEditorPackage}\"")
        }
    }

    compileOptions {
        setCoreLibraryDesugaringEnabled(true)
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }

    buildFeatures {
        compose true
        buildConfig true
    }
}

dependencies {
    coreLibraryDesugaring(libs.desugar.jdk.libs.nio)
    implementation(libs.commons.compress)
    implementation(libs.xz)
    implementation(libs.kotlinx.serialization.json)
    implementation libs.androidx.core.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.activity.compose
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.ui.graphics
    implementation libs.androidx.compose.ui.tooling.preview
    implementation libs.androidx.compose.material3
    implementation libs.androidx.documentfile
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation platform(libs.androidx.compose.bom)
    androidTestImplementation libs.androidx.compose.ui.test.junit4
    debugImplementation libs.androidx.compose.ui.tooling
    debugImplementation libs.androidx.compose.ui.test.manifest
}
